const PREFIX = 'app/global/';
export default {
  CHECK_AUTH: PREFIX + 'CHECK_AUTH',
  SET_CURRENT_USER: PREFIX + 'SET_CURRENT_USER',
  UPDATE_CURRENT_USER: PREFIX + 'UPDATE_CURRENT_USER',
  // Widgets
  FETCH_WIDGETS: PREFIX + 'FETCH_WIDGETS',
  SET_WIDGETS: PREFIX + 'SET_WIDGETS',
  SET_WIDGET_SEARCH_TERM: PREFIX + 'SET_WIDGET_SEARCH_TERM',
  FETCH_USER_WIDGETS: PREFIX + 'FETCH_USER_WIDGETS',
  TOGGLE_IS_FETCHING_USER_WIDGETS: PREFIX + 'TOGGLE_IS_FETCHING_USER_WIDGETS',
  SET_USER_WIDGETS: PREFIX + 'SET_USER_WIDGETS',
  SET_USER_WIDGET_SEARCH_TERM: PREFIX + 'SET_USER_WIDGET_SEARCH_TERM',
}