const PREFIX = 'app/global/';
export default {
  CHECK_AUTH: PREFIX + 'CHECK_AUTH',
  SET_CURRENT_USER: PREFIX + 'SET_CURRENT_USER',
  // Widgets
  FETCH_WIDGETS: PREFIX + 'FETCH_WIDGETS',
  SET_WIDGETS: PREFIX + 'SET_WIDGETS',
  SET_WIDGET_SEARCH_TERM: PREFIX + 'SET_WIDGET_SEARCH_TERM',
  // FORMS
  // ON_SUBMIT_REGISTER_FORM: PREFIX + 'ON_SUBMIT_REGISTER_FORM',
  // ON_SUBMIT_LOGIN_FORM: PREFIX + 'ON_SUBMIT_LOGIN_FORM',
  // ON_SUBMIT_FORGOT_PASSWORD: PREFIX + 'ON_SUBMIT_FORGOT_PASSWORD',
  // ON_SUBMIT_CHANGE_PASSWORD: PREFIX + 'ON_SUBMIT_CHANGE_PASSWORD',
}