const PREFIX = 'app/global/';
export default {
  CHECK_AUTH: PREFIX + 'CHECK_AUTH',
  SET_CURRENT_USER: PREFIX + 'SET_CURRENT_USER',
  // Widgets
  FETCH_WIDGETS: PREFIX + 'FETCH_WIDGETS',
  SET_WIDGETS: PREFIX + 'SET_WIDGETS',
  SET_WIDGET_SEARCH_TERM: PREFIX + 'SET_WIDGET_SEARCH_TERM'
}