const PREFIX = 'app/widgets/';
export default {
  FETCH_WIDGETS: PREFIX + 'FETCH_WIDGETS',
  SET_WIDGETS: PREFIX + 'SET_WIDGETS',
  SET_WIDGET_SEARCH_TERM: PREFIX + 'SET_WIDGET_SEARCH_TERM',
  FETCH_USER_WIDGETS: PREFIX + 'FETCH_USER_WIDGETS',
  TOGGLE_IS_FETCHING_USER_WIDGETS: PREFIX + 'TOGGLE_IS_FETCHING_USER_WIDGETS',
  SET_USER_WIDGETS: PREFIX + 'SET_USER_WIDGETS',
  SET_USER_WIDGET_SEARCH_TERM: PREFIX + 'SET_USER_WIDGET_SEARCH_TERM',
  // Modals
  TOGGLE_IS_CREATE_WIDGET_MODAL_OPEN: PREFIX + 'TOGGLE_IS_CREATE_WIDGET_MODAL_OPEN',
  TOGGLE_IS_CREATING_WIDGET: PREFIX + 'TOGGLE_IS_CREATING_WIDGET',
  TOGGLE_IS_UPDATE_WIDGET_MODAL_OPEN: PREFIX + 'TOGGLE_IS_UPDATE_WIDGET_MODAL_OPEN',
  TOGGLE_IS_UPDATING_WIDGET: PREFIX + 'TOGGLE_IS_UPDATING_WIDGET',
  ON_CREATE_NEW_WIDGET: PREFIX + 'ON_CREATE_NEW_WIDGET',
  ON_UPDATE_WIDGET: PREFIX + 'ON_UPDATE_WIDGET',
  ON_DELETE_WIDGET: PREFIX + 'ON_DELETE_WIDGET'
}